### ISSUE TITLE
Add JavaScript support to JFXScad and/or VRL-Studio

### ISSUE THREAD

**Issue by miho** [chriscamacho/JcsgFX#1]
First of all,  thanks for using my [JCSG](https://github.com/miho/JCSG) library :) 

> For my personal tastes JFXScad had lots of dependencies that could be done without, additionally for me JavaScript seemed a better fit than Groovy.

My proposal: Let's add JavaScript support to [JFXScad](https://github.com/miho/JFXScad) and/or the JCSG plugin for [VRL-Studio](http://vrl-studio.mihosoft.eu).

Let me point out a few things regarding language choice and dependencies:

> to embed and using Java objects in JavaScript is equally trivial...

For simpler use cases, this is mostly true. 

Even though it might not be evident from the simple JFXScad IDE, the interaction between Groovy, Java and the JVM are much deeper, though. Especially the fact that the Reflection API is usable directly on Java and Groovy objects alike, and that the Groovy compiler can compile mixed *.groovy and *.java code makes it a good fit for me. I use it to automatically create interactive visualizations of the source code which actually show intermediate CSG objects. Additionally, I use Groovy AST transformation for visualization of the control- and dataflow. This is really cool stuff :) 

image removed

image removed

See the video below for a demonstration:
- https://youtu.be/13lv_rbbvCI?t=11m11s  Reflection API (11m)
- https://youtu.be/13lv_rbbvCI?t=20m13s  AST Transformations (20m)
- http://vrl-studio.mihosoft.eu/                    IDE I use for working with JCSG

The other dependencies that you didn't like are mostly related to advanced text editors etc. that are not used much at the moment. But eventually JFXScad will inherit these features from VRL-Studio.

I understand that it is tempting to build a new editor/front-end for your language of choice. I love such things too :) But it would be even cooler if you'd contribute JavaScript support to JFXScad or even VRL-Studio.

As an additional note, an experimental and unpublished version of JCSG uses JavaScript internally ;)

**Comment by chriscamacho** [comment]
Unable to use 3d contexts on vrl-studio with my hardware, so won't be able to contribute.
My hardware can cope happily with javafx and lwjgl3 but I've never had much luck with j3d...

As this is an issue tracker for JcsgFX and not "JFXScad and/or VRL-Studio" I'm closing this.
